var app = document.getElementById('app');

var typewriter = new Typewriter(app, {
  loop: true,
  delay: 75,
});

typewriter
  .pauseFor(2000)
  .typeString('Assallamualaikum dek..')
  .pauseFor(1000)
  .deleteAll(20)
  .typeString('Bagaimana kabarmu disana?')
  .pauseFor(1000)
  .deleteAll(20)
  .typeString('Semoga kamu sehat - sehat selalu disana ya..')
  .pauseFor(1000)
  .typeString(' Amin...')
  .pauseFor(1000)
  .deleteAll(20)
  .typeString('Anu Dek, mas pengen di <strong>Pangku</strong>')
  .pauseFor(300)
  .deleteChars(10)
  .typeString(' eh anu, mas pengen di <strong>kokop</strong> ')
  .typeString('sama kamu dek..')
  .pauseFor(500)
  .typeString(' hehehe')
  .pauseFor(1000)
  .deleteAll(20)
  .typeString('Gak dek, becanda doank kok..')
  .pauseFor(2000)
  .deleteAll(20)
  .typeString('Mas mau bincang - bincang dikit gpp kan dek?')
  .pauseFor(2000)
  .deleteAll(20)
  .typeString('Kenapa ya dek?')
  .pauseFor(300)
  .typeString(' Mas kok keinget kamu terus dek?')
  .pauseFor(300)
  .deleteAll(20)
  .typeString('Maaf ya dek kalo mas ingkar janji..')
  .pauseFor(1000)
  .typeString(' Maaf mas cuma omong doank..')
  .pauseFor(1000)
  .deleteAll(20)
  .typeString('Maaf dah bikin kamu kecewa dek..')
  .pauseFor(1000)
  .typeString(' Maaf slalu bikin kamu sedih..')
  .pauseFor(1000)
  .deleteAll(20)
  .typeString('Tapi aku harap kamu bisa jadi lebih baik dari sebelumnya ya dek ya')
  .pauseFor(1000)
  .deleteAll(20)
  .typeString('Aku akui aku salah dek,')
  .pauseFor(300)
  .typeString(' aku jahat, gak seperti yang kamu harapkan..')
  .pauseFor(2000)
  .deleteAll(20)
  .pauseFor(1000)
  .typeString('Mungkin saja sekarang kamu dah bisa lupain aku..')
  .pauseFor(1000)
  .deleteAll(20)
  .pauseFor(1000)
  .typeString('Semoga bisa bahagia disana ya dek ya..')
  .pauseFor(300)
  .deleteAll(20)
  .pauseFor(300)
  .typeString('Maaf sebelumnya ya,')
  .pauseFor(300)
  .typeString(' maaf kalo dulu aku ngilang gitu aja')
  .typeString(' tanpa kabar dan tanpa penjelasan..')
  .pauseFor(300)
  .deleteAll(20)
  .pauseFor(1000)
  .typeString('Bukannya aku gak mau ngabarin atau gimana - gimana ya..')
  .pauseFor(300)
  .deleteAll(20)
  .pauseFor(1000)
  .typeString('Jujur aja aku juga gak bisa kek gitu, ')
  .pauseFor(300)
  .typeString('pengen nya selalu ngabarin kamu terus..')
  .pauseFor(300)
  .deleteAll(20)
  .typeString('Tapi aku sadar, ')
  .pauseFor(300)
  .typeString('gak mungkin kita bisa bersama..')
  .pauseFor(1000)
  .deleteAll(20)
  .pauseFor(300)
  .typeString('Setelah aku cerita ke mamakku, ke masku, ')
  .pauseFor(200)
  .typeString('semua pada gak ngebolehin..🥺')
  .pauseFor(300)
  .deleteAll(20)
  .pauseFor(200)
  .typeString('Mulai saat itu aku males mau ngapa - ngapain..')
  .pauseFor(200)
  .typeString(' Ga ada semangat sama sekali..')
  .deleteAll(20)
  .pauseFor(1000)
  .typeString('Aku udah jelasin semuanya,')
  .typeString('udah berusaha semampuku,')
  .typeString('tapi mereka tetep aja gak bisa ngertiin..')
  .pauseFor(300)
  .deleteAll(20)
  .pauseFor(1000)
  .typeString('Gak tau mau kek mana lagi aku dek..')
  .pauseFor(300)
  .typeString(' Maafkan aku yang gagal membujuk mereka dek..')
  .pauseFor(300)
  .deleteAll(20)
  .pauseFor(1000)
  .typeString('Jujur aja aku juga sakit dek, ')
  .pauseFor(300)
  .typeString('kenapa aku selalu gagal? kenapa harus aku?')
  .pauseFor(300)
  .deleteAll(20)
  .typeString('Takdir apa emang udah garisnya kek gini?')
  .pauseFor(1000)
  .deleteAll(20)
  .typeString('Tapi ya sudah lah, mau gimana lagi..😊')
  .pauseFor(1000)
  .deleteAll(20)
  .typeString('Kamu pasti mikirnya aku udah ada cewe atau udah dijodohin kan?')
  .pauseFor(1000)
  .deleteAll(20)
  .typeString('enggak dek,')
  .pauseFor(300)
  .typeString(' aku gak ngechat kamu karna aku coba melupakan semuanya..')
  .pauseFor(1000)
  .deleteAll(20)
  .typeString('Dah gak tau arah hidupku mau kemana..')
  .pauseFor(300)
  .typeString(' pasrah aja sama yang diatas..')
  .pauseFor(1000)
  .deleteAll(20)
  .typeString('Makasih ya dek untuk semua waktu yang ')
  .typeString('udah kamu berikan, perhatianmu, kesabaranmu, kasih sayangmu..')
  .pauseFor(300)
  .typeString(' Pokoknya makasih banget buat semuanya.. 🙏')
  .pauseFor(1000)
  .deleteAll(20)
  .typeString('Pasti kamu bakal menilai kalau aku alay ')
  .typeString('atau lebay atau apa lah itu karna aku buat - buat kek ginian 😁')
  .pauseFor(1000)
  .deleteAll (20)
  .typeString('Gpp kok dek,')
  .pauseFor(300)
  .typeString(' gimana kamu menilainya aja..')
  .pauseFor(1000)
  .deleteAll(20)
  .typeString('Aku harap kamu bisa ngerti setelah kamu membaca semua ini ya dek..')
  .pauseFor(1000)
  .deleteAll(20)
  .typeString('Ya udah gitu aja ya dek..')
  .pauseFor(1000)
  .deleteAll(20)
  .typeString('Jaga diri baik - baik ya disana')
  .pauseFor(1000)
  .deleteAll(20)
  .typeString('Salam buat semuanya ya..😊')
  .pauseFor(300)
  .deleteAll(20)
  .typeString('lobe u dek..🤙🤙🤙')
  .pauseFor(2000)
  
  
  .pauseFor(2000)
  .start();
